# Generated by Django 5.2.17 on 2026-08-12 08:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mahalla', '0002_infratuzulmataxlili_asphalt_lines_and_more'),
        ('rayon', '0002_alter_rayon_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Name')),
                ('owner', models.CharField(default='', max_length=200, verbose_name='Owner')),
                ('crop', models.CharField(default='', max_length=100, verbose_name='Crop')),
                ('area_hectares', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Area (ha)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('plot', models.JSONField(blank=True, default=dict, null=True, verbose_name='Plot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('mahalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_mahalla', to='mahalla.mahalla')),
            ],
            options={
                'verbose_name': 'Farmer',
                'verbose_name_plural': 'Farmers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Name')),
                ('condition', models.CharField(choices=[('asphalt', 'Asfalt'), ('gravel', 'Shagʻal'), ('dirt', 'Tuproq')], default='asphalt', max_length=20, verbose_name='Condition')),
                ('path', models.JSONField(blank=True, default=dict, null=True, verbose_name='Path')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('rayon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='road_rayon', to='rayon.rayon')),
            ],
            options={
                'verbose_name': 'Road',
                'verbose_name_plural': 'Roads',
                'ordering': ['-created_at'],
            },
        ),
    ]
