# Generated by Django 5.2.17 on 2026-08-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='farmer_images/', verbose_name='Photo'),
        ),
    ]
