# Generated by Django 6.0.6 on 2026-06-17 12:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rayon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('plot', models.JSONField(blank=True, default=dict, null=True, verbose_name='Plot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('rayon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahalla_rayon', to='rayon.rayon', verbose_name='Rayon')),
                ('staff', models.ManyToManyField(related_name='mahalla_staff', to=settings.AUTH_USER_MODEL, verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Mahalla',
                'verbose_name_plural': 'Mahallaler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InfratuzulmaTaxlili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umumiy_maydon', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Umumiy_maydon')),
                ('aholi_zichligi', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Aholi_zichligi')),
                ('yollar_uzunligi', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Yollar_uzunligi')),
                ('elektr_uzulishlari', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Elektr_uzulishlari')),
                ('gaz_bilantaminlanganlar', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Gaz_bilantaminlanganlar')),
                ('asfaltlangan_yollar_ulushi', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Asfaltlangan_yollar_ulushi')),
                ('internet_koplami_va_tezligi', models.CharField(default='', max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Internet_koplami_va_tezligi')),
                ('omborxonalar', models.CharField(default='', max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Omborxonalar')),
                ('suvgorish_kanallari_betonlash', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Suvgorish_kanallari_betonlash')),
                ('suvgoriladigan_er_maydoni', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Suvgoriladigan_er_maydoni')),
                ('toza_ichimlik_suv_taminoti', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Toza_ichimlik_suv_taminoti')),
                ('kanalizacia_tarmogi', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Kanalizacia_tarmogi')),
                ('elektr_tarmoqlari_modernizaciasi', models.TextField(default='', validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Elektr_tarmoqlari_modernizaciasi')),
                ('foydali_qazilmalar_konlari', models.CharField(default='', max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Foydali_qazilmalar_konlari')),
                ('davlat_dasturlariga_muvofiqlik', models.TextField(default='', validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Davlat_dasturlariga_muvofiqlik')),
                ('sanoat_zonasi_er_foydalanish', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Sanoat_zonasi_er_foydalanish')),
                ('investiciya_jalb_qilish_bajarilishi', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Investiciya_jalb_qilish_bajarilishi')),
                ('qurilish_materyallari_klasteri', models.TextField(default='', validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Qurilish_materyallari_klasteri')),
                ('mahalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infratuzulmataxlili_mahalla', to='mahalla.mahalla', verbose_name='Mahalla')),
            ],
        ),
        migrations.CreateModel(
            name='AholiVaBandlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aholi_soni', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Aholi soni')),
                ('oylalar_soni', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Oylalar soni')),
                ('honadonlar_soni', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Honadonlar soni')),
                ('kambagallik_darajasi', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Kambagallik darajasi')),
                ('rasmiy_ishsizlik_darajasi', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Rasmi ishsizlik darajasi')),
                ('ishsizlar_soni', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ishsizlar soni')),
                ('haqiqi_ishsizlik_darajasi', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Haqiqi ishsizlik darajasi')),
                ('mehnat_resurslari', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Mehnat resurslari')),
                ('band_aholi', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Band Aholi')),
                ('rasmiy_royxatdagi_ishchilar', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Rasmi royxatdagi_ishchilar')),
                ('norasmi_sektorda_bandlik', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Norasmi sektorda_bandlik')),
                ('horiijga_ketkan_migrantlar', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Horiijga ketkan_migrantlar')),
                ('urtacha_oylik_maosh', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Urtacha oylik maosh')),
                ('yoshlar_ishsizligi', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Yoshlar ishsizligi')),
                ('ayollar_ishsizligi', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ayollar ishsizligi')),
                ('nogironlar_soni_va_bandligi', models.CharField(default='', max_length=500, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(500)], verbose_name='Nogironlar_soni_va_bandligi')),
                ('ijtimoyi_himoyaga_muqtoj_aholi', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ijtimoyi himoyaga_muqtoj_aho')),
                ('kam_taminlangan_oylalar', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Kam_taminlangan_oylalar')),
                ('kambagal_oylalar_soni', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Kambagal_oylalar_soni')),
                ('tugilish_mirgacia_dinamikasi', models.CharField(default='', max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Tugilish/mirgacia_dinamikasi')),
                ('ogir_kasallik_holatlari', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ogir_kasallik_holatlari')),
                ('qaytgan_migrantlar_soni', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Qaytgan_migrantlar_soni')),
                ('ishsizlik_ish_orni_yaratish_scenariylari', models.TextField(default='', validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1000)], verbose_name='Ишсизлик/иш ўрни яратишa сценарийлари')),
                ('norasmiy_sektorda_yillik_soliq_yuqotish', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Норасмий секторда йиллик солиқ йўқотиш')),
                ('bola_nafaqa_oluvchilar', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Bola_nafaqa_oluvchilar')),
                ('mahalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aholivabandlik_mahalla', to='mahalla.mahalla', verbose_name='Mahalla')),
            ],
        ),
    ]
