# Generated by Django 5.2.17 on 2026-08-14 09:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahalla', '0002_infratuzulmataxlili_asphalt_lines_and_more'),
        ('rayon', '0002_alter_rayon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aholivabandlik',
            name='ayollar_soni',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ayollar soni'),
        ),
        migrations.AddField(
            model_name='aholivabandlik',
            name='erkaklar_soni',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Erkaklar soni'),
        ),
        migrations.AddField(
            model_name='aholivabandlik',
            name='rayon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aholivabandlik_rayon', to='rayon.rayon', verbose_name='Rayon'),
        ),
        migrations.AddField(
            model_name='aholivabandlik',
            name='yosh_0_18',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='0-18 yosh'),
        ),
        migrations.AddField(
            model_name='aholivabandlik',
            name='yosh_0_6',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='0-6 yosh'),
        ),
        migrations.AddField(
            model_name='aholivabandlik',
            name='yosh_14_30',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='14-30 yosh'),
        ),
        migrations.AddField(
            model_name='aholivabandlik',
            name='yosh_60_plus',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='60+ yosh'),
        ),
        migrations.AddField(
            model_name='infratuzulmataxlili',
            name='issiqxonalar_soni',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Issiqxonalar soni'),
        ),
        migrations.AddField(
            model_name='infratuzulmataxlili',
            name='kochalar_soni',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Koʻchalar soni'),
        ),
        migrations.AddField(
            model_name='infratuzulmataxlili',
            name='rayon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infratuzulmataxlili_rayon', to='rayon.rayon', verbose_name='Rayon'),
        ),
        migrations.AddField(
            model_name='infratuzulmataxlili',
            name='tomorqali_honadonlar',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tomorqasi bor xonadonlar'),
        ),
        migrations.AddField(
            model_name='tadbirkorlar',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='aholivabandlik',
            name='mahalla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aholivabandlik_mahalla', to='mahalla.mahalla', verbose_name='Mahalla'),
        ),
        migrations.AlterField(
            model_name='infratuzulmataxlili',
            name='mahalla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infratuzulmataxlili_mahalla', to='mahalla.mahalla', verbose_name='Mahalla'),
        ),
    ]
