# Generated by Django 5.2.17 on 2026-08-14 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahalla', '0003_aholivabandlik_ayollar_soni_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahalla',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='mahalla_staff', to=settings.AUTH_USER_MODEL, verbose_name='Staff'),
        ),
    ]
