# Generated by Django 6.0.6 on 2026-06-17 12:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Rayon')),
                ('region', models.CharField(default='Qoraqalpogʻiston', max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Region')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('plot', models.JSONField(blank=True, default=dict, null=True, verbose_name='Plot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rayon_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rayon',
                'verbose_name_plural': "Rayon's",
                'ordering': ['-created_at'],
            },
        ),
    ]
