# Generated by Django 5.2.17 on 2026-08-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rayon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rayon',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
